/**
 * Cricket Trivia Question Types
 * 
 * Defines the structure for cricket trivia questions generated by AI
 * and managed throughout the application.
 */

export type DifficultyLevel = 'easy' | 'medium' | 'hard';

export type QuestionCategory = 
  | 'legendary_moments'
  | 'player_stories' 
  | 'records_stats'
  | 'rules_formats'
  | 'cultural_impact';

export interface TriviaQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number; // Index of correct option (0-3)
  explanation: string;
  category: QuestionCategory;
  difficulty: DifficultyLevel;
  source?: string; // Optional source reference
  generatedAt: Date;
}

export interface QuestionGenerationRequest {
  category: QuestionCategory;
  difficulty: DifficultyLevel;
  count?: number;
  includeExplanation?: boolean;
}

export interface QuestionValidationResult {
  isValid: boolean;
  errors: string[];
  suggestions?: string[];
}

export interface GameSession {
  id: string;
  mode: 'practice' | 'game';
  questions: TriviaQuestion[];
  currentQuestionIndex: number;
  score: number;
  startTime: Date;
  endTime?: Date;
}